version: '3.3'

services:
  db: # container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env # utilizando um arquivo de configuração para ler as variáveis de ambiente

      # Incluindo variaveis de ambiente dentro do arquivo diretamente

     #     environment:
     # WORDPRESS_DB_HOST: db:3306
     # WORDPRESS_DB_USER: matheus
     # WORDPRESS_DB_PASSWORD: secret
     # WORDPRESS_DB_NAME: wordpress

volumes: 
  db_data: {}