apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app # este é o link que vai expor nosso service ao deployment
  ports: 
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: LoadBalancer
